### ISSUE TITLE
Doesn't launch on Windows

### ISSUE THREAD

**Issue by Fredz66** [jimy-byerley/uimadcad#13]
I installed pymadcad with pip, the Microsoft build tools, downloaded and unziped uimadcad_0.6_x86_64.zip, launched Git Bash, cd to the madcad directory and typed ./madcad.bat and the result was :

```
C:\Users\frederic\AppData\Local\Programs\Python\Python311\python.exe
C:\Users\frederic\AppData\Local\Microsoft\WindowsApps\python.exe
Traceback (most recent call last):
  File "D:\Applications\madcad\madcad.bat\..\madcad", line 24, in <module>
    import launcher
ImportError: DLL load failed while importing launcher: Le module sp▒cifi▒ est introuvable.
```

**Comment by jimy-byerley** [comment]
Never tried to run it from a git bash, maybe that's something with it and finding the uimadcad folder path ...
Anyway, I would suggest installing `uimadcad` from [pypi](https://pypi.org/project/uimadcad/) using `pip` now that I made `uimadcad` opensource :) Could you give it a try ?

**Comment by Fredz66** [comment]
I installed it via pip and I could launch using :

` python -m uimadcad`

Thank you.
