### ISSUE TITLE
.bat file import module error 

### ISSUE THREAD

**Issue by Shrav108** [jimy-byerley/uimadcad#20]
Hi, I'm using uimadcad on windows. I am usng anaconda promt to launch the .bat file. When I do, I get module not found error with :
```
 File "C:\Users\SB\Downloads\madcad\madcad", line 24, in <module>
 import launcher
ImportError: DLL load failed while importing launcher: The specified module could not be found.
```
The launcher file is in the same directory. Why am i getting this error ?

**Comment by jimy-byerley** [comment]
I don't have a clue, I never used the anaconda prompt for this. maybe the default content of PYTHONPATH is not the same in this case ...
But reading it is about the `launcher` I guess you followed the installation instructions from the [webside](https://madcad.netlify.app/uimadcad). I should update them, but now you should instead use pip:

```shell
pip install pymadcad[stl,ply] uimadcad
python -m uimadcad
```
